language: r
cache: packages

r_binary_packages:
 - rgdal

r_github_packages:
  - r-lib/pkgdown

apt_packages:
  - libudunits2-dev
  - libgdal1-dev
  
after_success:
  - Rscript -e 'devtools::install()' # To install package
  - Rscript -e "pkgdown::build_site(preview = FALSE)"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  on:
    branch: master
