before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update --yes

language: r

dist: bionic

cache: packages

r_packages:
  - pkgdown

apt_packages:
  - libudunits2-dev
  - libgdal-dev
  - libproj-dev
  - libgeos-dev
  - libharfbuzz-dev
  - libfribidi-dev

after_success:
  - R CMD INSTALL . # Install the package to build vignettes
  - Rscript -e "pkgdown::build_site(preview = FALSE)"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
