before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

  language: r
cache: packages

r_packages:
  - pkgdown

after_success:
  - R CMD INSTALL . # Install the package to build vignettes
  - Rscript -e "pkgdown::build_site(preview = FALSE)"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
