language: r
sudo: required
cache: packages

r_binary_packages:
 - rgdal

r_github_packages:
  - r-lib/pkgdown

addons:
  apt:
    packages:
      - libudunits2-dev

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libgdal1-dev
  
after_success:
  - Rscript -e "pkgdown::build_site(preview = FALSE)"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  on:
    branch: master
